import FirebaseProvider from "@/providers/firebase";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const segoeUI = localFont({
  src: [
    {
      path: "./_fonts/Segoe-UI.woff2",
      weight: "400",
      style: "normal"
    },

    {
      path: "./_fonts/Segoe-UI-Bold.woff2",
      weight: "700",
      style: "normal"
    },
    {
      path: "./_fonts/Segoe-UI-Italic.woff2",
      weight: "400",
      style: "italic"
    },
    {
      path: "./_fonts/Segoe-UI-Bold-Italic.woff2",
      weight: "700",
      style: "italic"
    }
  ],
  variable: "--font-segoe"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProvider>{children}</FirebaseProvider>
      </body>
    </html>
  );
}
